server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #单个文件最大限制
      max-request-size: 25MB #最大请求限制
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.88.128:22122
ly:
  upload:
    baseUpLoad: http://image.leyou.com/
    allowType:
      - image/png
      - image/jpeg
      - image/jpg
      - image/bmp